package com.yx.po;

import java.io.Serializable;
import java.util.Date;

public class WorkerInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker_info.id
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker_info.username
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker_info.password
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker_info.number
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker_info.real_name
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker_info.sex
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker_info.birthday
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker_info.address
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker_info.tel
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker_info.email
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker_info.register_date
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    private Date registerDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker_info.worker_number
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    private String workerNumber;

    /**
     * 是否离职
     */
    private Integer status;

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 头像
     */
    private String avatar;

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table worker_info
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker_info.id
     *
     * @return the value of worker_info.id
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker_info.id
     *
     * @param id the value for worker_info.id
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker_info.username
     *
     * @return the value of worker_info.username
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker_info.username
     *
     * @param username the value for worker_info.username
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker_info.password
     *
     * @return the value of worker_info.password
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker_info.password
     *
     * @param password the value for worker_info.password
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker_info.real_name
     *
     * @return the value of worker_info.real_name
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker_info.real_name
     *
     * @param realName the value for worker_info.real_name
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker_info.sex
     *
     * @return the value of worker_info.sex
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker_info.sex
     *
     * @param sex the value for worker_info.sex
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker_info.birthday
     *
     * @return the value of worker_info.birthday
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker_info.birthday
     *
     * @param birthday the value for worker_info.birthday
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker_info.address
     *
     * @return the value of worker_info.address
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker_info.address
     *
     * @param address the value for worker_info.address
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker_info.tel
     *
     * @return the value of worker_info.tel
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker_info.tel
     *
     * @param tel the value for worker_info.tel
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker_info.email
     *
     * @return the value of worker_info.email
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker_info.email
     *
     * @param email the value for worker_info.email
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker_info.register_date
     *
     * @return the value of worker_info.register_date
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker_info.register_date
     *
     * @param registerDate the value for worker_info.register_date
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker_info.worker_number
     *
     * @return the value of worker_info.worker_number
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    public String getWorkerNumber() {
        return workerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker_info.worker_number
     *
     * @param workerNumber the value for worker_info.worker_number
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2021
     */
    public void setWorkerNumber(String workerNumber) {
        this.workerNumber = workerNumber == null ? null : workerNumber.trim();
    }
}