package com.yx.dao;

import com.yx.po.WorkerInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WorkerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker_info
     *
     * @mbggenerated Wed Apr 19 17:37:51 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker_info
     *
     * @mbggenerated Wed Apr 19 17:37:51 CST 2023
     */
    int insert(WorkerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker_info
     *
     * @mbggenerated Wed Apr 19 17:37:51 CST 2023
     */
    int insertSelective(WorkerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker_info
     *
     * @mbggenerated Wed Apr 19 17:37:51 CST 2023
     */
    WorkerInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker_info
     *
     * @mbggenerated Wed Apr 19 17:37:51 CST 2023
     */
    int updateByPrimaryKeySelective(WorkerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker_info
     *
     * @mbggenerated Wed Apr 19 17:37:51 CST 2023
     */
    int updateByPrimaryKey(WorkerInfo record);

    /**
     * 查询所有记录信息
     */
    List<WorkerInfo> queryAllWorkerInfo(WorkerInfo workerInfo);

    /**
     * 根据用户名和密码查询用户信息
     */
    WorkerInfo queryUserInfoByNameAndPassword(@Param("username") String username, @Param("password") String password);

    /**
     * 根据工号和密码查询用户信息
     */
    WorkerInfo queryUserInfoByWorkerNumberAndPassword(@Param("workerNumber") String workerNumber, @Param("password") String password);
}